#! /usr/bin/env ruby

require "rubygems"
require "daemons"
require "optparse"
require 'json'
require File.expand_path("../../lib/beetle", File.dirname(__FILE__))

tmp_path = File.expand_path("../../tmp", File.dirname(__FILE__))

Daemons.run_proc("beetle_handler", :log_output => true, :dir_mode => :normal, :dir => tmp_path) do
  opts = OptionParser.new

  opts.on("-f", "--redis-master-file path", String) do |val|
    Beetle.config.redis_server = val
  end

  opts.parse!(ARGV - ["start", "--"])

  Beetle.config.servers = "127.0.0.1:5672" # rabbitmq

  # set Beetle log level to info, less noisy than debug
  Beetle.config.logger.level = Logger::INFO

  client = Beetle::Client.new.configure :auto_delete => true do |config|
    config.queue(:echo, :lazy => true, :dead_lettering => true)
    config.message(:echo)
    config.handler(:echo) do |message|
      begin
        client.deduplication_store.redis.server
      rescue
        master_file_content = File.read(Beetle.config.redis_server)
        "no redis master: exception: #{$!.class}(#{$!}), master_file: '#{master_file_content}'"
      end
    end
    config.handler(Beetle.config.beetle_policy_updates_queue_name) do |message|
      begin
        Beetle.config.logger.info "received beetle policy update message': #{message.data}"
        client.set_queue_policies!(JSON.parse(message.data))
      rescue => e
        Beetle.config.logger.error("#{e}:#{e.backtrace.join("\n")}")
      end
    end
  end
  client.listen do
    puts "Started beetle handler for system: #{Beetle.config.system_name}"
  end
end
