#! /usr/bin/env ruby

require "rubygems"
require "daemons"
require "optparse"
require File.expand_path("../../lib/beetle", File.dirname(__FILE__))

tmp_path = File.expand_path("../../tmp", File.dirname(__FILE__))

Daemons.run_proc("beetle_handler", :log_output => true, :dir_mode => :normal, :dir => tmp_path) do
  opts = OptionParser.new

  opts.on("-f", "--redis-master-file path", String) do |val|
    Beetle.config.redis_server = val
  end

  opts.parse!(ARGV - ["start", "--"])

  Beetle.config.servers = "#{ENV['RABBITMQ_HOST'] || '127.0.0.1'}:#{ENV['RABBITMQ_PORT'] || 5672}" # rabbitmq

  # set Beetle log level to info, less noisy than debug
  Beetle.config.logger.level = Logger::INFO

  client = Beetle::Client.new.configure :auto_delete => true do |config|
    config.queue(:echo)
    config.message(:echo)
    config.handler(:echo) {|message| client.deduplication_store.redis.server rescue "no redis master"}
  end
  client.listen do
    puts "Started beetle handler"
  end
end
