#! /usr/bin/env ruby

require "rubygems"
require "daemons"
require "optparse"
require File.expand_path("../../lib/beetle", File.dirname(__FILE__))

Daemons.run_proc("beetle_handler", :log_output => true) do
  opts = OptionParser.new

  opts.on("-f", "--redis-master-file path", String) do |val|
    Beetle.config.redis_master_file = val
  end

  opts.parse!(ARGV - ["start", "--"])

  Beetle.config.servers = "localhost:5672, localhost:5673" # rabbitmq

  # set Beetle log level to info, less noisy than debug
  Beetle.config.logger.level = Logger::INFO

  client = Beetle::Client.new
  client.register_queue(:echo)
  client.purge(:echo)
  client.register_message(:echo)
  client.register_handler(:echo) {|message| client.deduplication_store.redis.server rescue "no redis master"}
  puts "Started beetle handler"
  client.listen
end
