#! /usr/bin/env ruby

require "rubygems"
require "daemons"
require File.expand_path("../../lib/beetle", File.dirname(__FILE__))

tmp_path = File.expand_path("../../tmp", File.dirname(__FILE__))
system_notification_log_file_path = "#{tmp_path}/system_notifications.log"

Daemons.run_proc("system_notification_logger", :log_output => true, :dir_mode => :normal, :dir => tmp_path) do
  Beetle.config.servers = "localhost:5672, localhost:5673" # rabbitmq

  # set Beetle log level to info, less noisy than debug
  Beetle.config.logger.level = Logger::DEBUG

  client = Beetle::Client.new
  client.configure :exchange => :system, :auto_delete => true do |config|
    config.message  :system_notification
    config.queue    :system_notification
    config.handler  :system_notification do |message|
      payload = ActiveSupport::JSON.decode(message.data)
      text = payload["message"]
      puts "Writing message to #{system_notification_log_file_path}: #{text}"
      File.open(system_notification_log_file_path, "a") do |f|
        f << text
      end
    end
  end
  puts "Started system notification logger"
  client.listen
end
