#!/bin/bash
if test $# -eq 0 ; then
    echo "beetled: need a program to run"
    exit 1
fi
program=$1
if test -x $program ; then
    $program "$@" &
else
    echo "beetled: $program it not an executable"
    exit 1
fi
exit 0

