services:
  redis:
    image: "redis:6.0"
    command: redis-server --tls-port 6379 --port 0  --tls-auth-clients no --tls-cert-file /tls/test_redis.crt --tls-key-file /tls/test_redis.key --tls-ca-cert-file /tls/test_ca.crt
    container_name: redis-tls
    ports:
      - 6379:6379
    volumes:
      - ./docker/tls:/tls
