language: ruby
bundler_args: --without development
before_script: ./bin/ci/before_build
script: "bundle exec rake spec:ci"
env:
  - CI=true
rvm:
  - 2.3.3
  - 2.4.1
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
notifications:
  recipients:
    - michael@rabbitmq.com
branches:
  only:
    - master
    - 1.7.x-stable
matrix:
  allow_failures:
    - rvm: jruby
      gemfile: gemfiles/eventmachine-pre

services:
  - rabbitmq
