#!/usr/bin/env ruby
require 'rubygems'
require 'optparse'

options = { }
OptionParser.new do |opt|
  opt.banner = "Usage: console [options]"
  opt.on("--debugger", 'Enable ruby-debugging for the console.') { |v| options[:debugger] = v }
  opt.parse!(ARGV)
end

libs =  " -r irb/completion"
libs << %( -r #{Fileexpand_path("../../lib/beetle.rb",__FILE__)})

if options[:debugger]
  begin
    require 'ruby-debug'
    libs << " -r ruby-debug"
    puts "=> Debugger enabled"
  rescue Exception
    puts "You need to install ruby-debug to run the console in debugging mode. With gems, use 'gem install ruby-debug'"
    exit
  end
end

irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'
exec "#{irb} #{libs} --simple-prompt"
