name: build gobeetle

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Upgrade Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Install dependencies
        run: sudo apt-get install redis

      - name: Start required services
        run: docker compose up -d

      - name: Compile and test beetle go binary
        run: make  && make test-main

      - name: Collect Docker Logs
        uses: jwalton/gh-docker-logs@v2.2.0
        if: failure()
        with:
          images: 'rabbitmq'

      - name: Stop services
        run: docker compose down
 
