name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - head
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
          - '2.3'
          - jruby-head
          - jruby-9.3
          - jruby-9.2
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake

  legacy-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.2'
          - '2.1'
          - '2.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake
